### ISSUE TITLE
for Build the same Application with new JSON

### ISSUE THREAD

**Issue by yazik12** [lindalevanen/GiffyChat#1]
Hello Dear, i hope that you are will.
i'm glade for this sacrifice that you are doing it's great.
i'm a developer beginner and i hope to learn how to build the same Application, and how to work with the JASON of firebase in this case.
thank you so much for this work, i hope get you replay the near possible.

**Comment by lindalevanen** [comment]
Hello!

Sorry for the late response, I'm glad to hear if my code helps in any way!

I really recommend to explore the different ways of creating the chat functionality, this is a really early project of mine on my road of Android development, so it might be that there are better ways for instant messaging than just using the Firebase Database API.

But if you want to follow my footsteps, then I recommend getting yourself familiar with the different Firebase APIs (Auth, Database, Storage), and also find a good recent tutorial on how to make the chat UI (I recommend using RecyclerView instead of ListView for the messages list).

Good luck! :)
